[deps]
GradedUnitRanges = "e2de450a-8a67-46c7-b59c-01d5a3d041c5"
LabelledNumbers = "f856a3a6-4152-4ec4-b2a7-02c1a55d7993"

[sources]
LabelledNumbers = {url = "https://github.com/ITensor/LabelledNumbers.jl"}
